Fix !rank command logic
kiwec/osu-ranked-lobbies pull request #31
Opened 2021-12-24 02:33 UTC by coozieki

2021-12-24 02:47 UTC, kiwec requested changes

2021-12-24 02:47 UTC, kiwec commented on ranked.js
> +          await bancho.whois(requested_username);
Not doing anything with that? Should be getting the user from the database with that ID (if we have them in the database).

2021-12-24 03:38 UTC, coozieki commented on ranked.js
> +          await bancho.whois(requested_username);
Fixed

2021-12-25 07:17 UTC, kiwec approved these changes

2021-12-25 07:17 UTC, merged